### ISSUE TITLE
(optionally) reduce image quality

### ISSUE THREAD

**Issue by TiddoLangerak** [inventid/iaas#102]
IAAS currently keeps images in the highest possible quality, but for web usages this isn't ideal. On Magnet.me for example it is noticeable that it takes time to download all the images (especially on mobile), and speed tools also generally suggest that we compress more (e.g. PageSpeed Insights says we can save between 40 and 70% on our image sizes, depending on which page you feed it, the Magnet.me company page could even save 5.6MB!). It would be nice if we could reduce the image quality for smaller image sizes.

**Comment by rogierslag** [comment]
> the Magnet.me company page could even save 5.6MB!

Note that most of this comes from the non-optimized versions of the opengraph images (which do not go through iaas).

We could reduce the quality if we want to by an optional `quality` query parameter though

**Comment by TiddoLangerak** [comment]
Closed through #103
