### ISSUE TITLE
Better image compression

### ISSUE THREAD

**Issue by TiddoLangerak** [inventid/iaas#115]
When running Magnet.me through Google's PageSpeed then it suggest that we still can save quite a lot of bandwith by better compressing images (somewhere between 10 and 50% usually). This goes both for `png` and `jpg`. Looking at Google's page for [Optimizing Images](https://developers.google.com/speed/docs/insights/OptimizeImages) then I think we're still missing the following optimizations:

### PNG
- Remove alpha channel if all pixels are opaque
- Strip metadata (this actually saves surprisingly much on some images) 

### JPEG
- Reduce chroma sampling
- Strip meta data

On image heavy pages (like magnet.me/a/companies) this saves 100-150kb. On our react app this is about 15% of the entire page load.

**Comment by rogierslag** [comment]
1. You specifically mean stripping EXIF data?
1. I'd recommend against altering the sources too much (with the alpha channel stuff) since we had problems with PNG alpha channels in the past (especially if the source png is not really well compressed)

**Comment by rogierslag** [comment]
Additionally image sizes are less of a problem: loading of the page is not blocked (nor is rendering). HTML and late CSS worth addressing more probably.

And it might be an idea to prefetch the DNS etc for our CDN domains (which saves directly 20ms of all requests)

**Comment by TiddoLangerak** [comment]
> You specifically mean stripping EXIF data?

Yes, Google suggests to use the `-strip` parameter for imagemagick.

> Additionally image sizes are less of a problem

Specifically for react.magnet.me: Image size & server-response times (due to uncached SSR) are currently the only things Google's PageSpeed still reports. We already optimized all other render blocking/delaying content.

**Comment by rogierslag** [comment]
@TiddoLangerak Can you recheck whether this is still the case? All images have now been re-rendered.

According to https://stackoverflow.com/questions/7261855/recommendation-for-compressing-jpg-files-with-imagemagick we can still optimize a bit more. However I'm a bit hesitant about recompressing with a custom quality by default. It's already possible to set the quality parameter to reduce file sizes, and I think clients should request this themselves instead of determined by the service.

**Comment by TiddoLangerak** [comment]
Just tested a few pages with PageSpeed, and it still tells us that we can reduce the JPG sizes by 10-25% per image served from IAAS. PageSpeed only talkes about saving size by compression, so `srcset` and image size aren't the issue there (and this is also something that we already do mostly right at Magnet.me). 

I think it's mostly the chroma sampling that we do wrong, IAAS doesn't have support for that. I don't really have a strong preference about it being opt-in or default.

**Comment by AlexKolpa** [comment]
ImageMagick defines chroma sampling automatically based on the image quality specified. I just checked for our 60 quality, and that already uses a 4:1:1 subsampling. We could reduce this further but I'm not sure if it's worth the effort

**Comment by rogierslag** [comment]
Note that logos are still requested without `fit=canvas` for example, so the browser resizes them (removing the size constraints). The optimized versions from Google are properly scaled already (try downloading them).

So I think this is mostly a Magnet.me issue, and therefore this does not belong in this repo
