### ISSUE TITLE
Create a cache-eviction policy

### ISSUE THREAD

**Issue by alexnederlof** [inventid/iaas#4]
Simply delete images based on an evict policy. This should be configurable. Think of the Guava cache policies: evict on size reached, evict after write, and evict after read.

**Comment by rogierslag** [comment]
Do you mean on the AWS bucket? This is configurable using a LifeCycle on S3, but that would require S3 to contact the service to let it know what was deleted.

**Comment by rogierslag** [comment]
This has some problems, so leaving it as it is
